<?php

  // CURRENTLY a bit HACKY. clean up soon

require_once 'Image/GraphViz.php';
require_once 'MDB2.php';
require_once 'config/config.php';

class DBGraphNav_DBCon{

  function __construct() {
    $this->cfg = DBGraphNav_Config::getInstance();
  }

  function get_data($parentnode, $data_type) {
    foreach ($this->cfg->get_queries($parentnode, $data_type) as $qry){
      $db =& MDB2::connect($qry["DSN"]);
      if (PEAR::isError($db)) {
	die($db->getMessage().", \n".$db->getDebugInfo());
      }
      $db->setFetchMode(MDB2_FETCHMODE_ASSOC);

      //      $db->setLimit(10); //debugging, lowers server load
      $result =& $db->query($qry["query_string"]);
      if (PEAR::isError($result)) {
	die($result->getMessage());
      }
      while ($row = $result->fetchRow()) {
	$return[] =$row;
      }
    }
    return $return;
  }
}


class DBGraphNav_Network {

  function __construct() {
    $this->cfg = DBGraphNav_Config::getInstance();
    $this->db = new DBGraphNav_DBCon; //create the database connection
  }

  /*Assumes build_network has been called previously.
    
    Makes a dot representation of the data stored in the network class 
    variable.
   */
  function save_dot($output_filename) {
    $graph = new Image_Graphviz();

    //options.
    $opts =& $this->cfg->graphing['graphviz'];
    //$graph->binPath = $opts['binPath'];
    /* these 2 lines aren't usually necessary */
    //$graph->dotCommand = $opts['dotCommand'];
    //$graph->neatoCommand = $opts['neatoCommand'];
    $graph->graph = array('directed' =>(bool)$opts['directed'],
			  'strict'   =>(bool)$opts['strict'],
		 	  'name'     =>$opts['name'],
			 'attributes'=>$this->cfg->graphing['display_options']);

    //type
    foreach ($this->network as $type=>$value){
      //actual node
      foreach ($value as $id=>$value){
	/*This creates a unique name for each node. If this conflicts
	with a graphs naming scheme, it may be hashed instead. It is
	not currently hashed for performance reasons. The _escape
	function provides a graphviz-compatible ID.
	*/
	$cur_node = $graph->_escape("$type||||$id");
	$graph->addNode($cur_node,
			array('URL' => $value["callback_url"],
			      'label' => 
			      wordwrap($value["display_name"],
				   $this->cfg->graphing['misc']['wordwrap'])));
	//node neighbor type
	foreach ($value["neighbors"] as $type2=>$value2) {
	  //actual node neighbor
	  foreach ($value2 as $id2=>$display_val2){
	    $graph->addEdge(Array($cur_node => 
				     $graph->_escape("$type2||||$id2")));
	  }
	}
      }
    }
    $graph->saveParsedGraph($output_filename);
    //return $graph->image('png', 'neato');
    }
  
  //assumes build_network has been called. For debugging, mostly.
  function get_network() {
    return $this->network;
  }

  /*This builds the network object using SQL queries. It takes the
    tree structure generated by the queries and flattens it out into a
    form that is easily converted into a dot file.
   */
  function build_network($basenode, $type, $maxdepth = 5) {
    $a =& $this->network[$type][$basenode];
    $a['display_name']='BASE NODE'; //FIX ME
    $a['depth']=0;
    $a['neighbors'] =
      $this->build_network_helper($basenode, $type, $maxdepth, 1);
  }
  
  /*
    This seems functional now. It might appear simpler if it were
    re-written using purely tail recursion, but the tree recursion
    works.
  */
  private function build_network_helper($basenode, $type, $maxdepth, $depth) {
    $friends = array();
    if ($depth <= $maxdepth) {
	foreach ($this->db->get_data($basenode, $type) as $node) {
	  $a =& $this->network[$node['type']][$node['value']];
	  if (isset($a) ){
	    if ($a['depth'] > $depth) {
	      /* If we find a newer, shorter route to a max-depth
		 node, we want to pull the network where previously it
		 was not queried.
	      */
	      if ($a['depth'] >= $maxdepth) {
		// find neighbors
		$a['neighbors'] =  
		  $this->build_network_helper($node['value'],
					      $node['type'],
					      $maxdepth,
					      $depth + 1);
	      
	      }
	      //we should use the lower depth in any case
	      $a['depth']=$depth; 
	    }
	  } else { //otherwise, pull all the info
	    $a['display_name']=$node['display_name'];
	    $a['depth']=$depth;
	    $a['callback_url'] = $node['callback_url'];
	    $a['neighbors'] =  
	      $this->build_network_helper($node['value'],
					  $node['type'],
					  $maxdepth,
					  $depth + 1);
	  }
	  //store friends
	  $friends[$node['type']][$node['value']] = $node['display_name'];
	}
    }
    return $friends;
  }}
?>